export const SET_WELCOME_MESSAGE = 'SET_WELCOME_MESSAGE';
export const GET_WELCOME_MESSAGE = 'GET_WELCOME_MESSAGE';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const GET_API_INFO = 'GET_API_INFO';
export const SET_API_INFO = 'SET_API_INFO';
